
#服务名
spring:
  application:
    name: spring-cloud-consumer
  profiles:
    active: dev
#监控指标
management:
  server:
    #端口
    port: 8078
    servlet:
      context-path: /consumer
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
      health:
        enabled: true
        show-details: always
#注册中心地址及账号密码
eurekaServer:
  user: root
  password: root
hystrix:
  command:
    default:
      execution:
        isolation:
        thread:
        #毫秒单位
        timeoutInMilliseconds: 10000
eureka:
  instance:
    instance-id: localhost:${management.server.port}
    hostname: localhost
    prefer-ip-address: true
  client:
    prefer-ip-address: true
    #将此项目注册到Eureka服务
    register-with-eureka: true
    service-url:
      defaultZone: http://${eurekaServer.user}:${eurekaServer.password}@peer1:8761/eureka,http://${eurekaServer.user}:${eurekaServer.password}@peer2:8762/eureka,http://${eurekaServer.user}:${eurekaServer.password}@peer3:8763/eureka

info:
      status: OK