#服务名
spring:
  application:
    name: spring-cloud-provider
  profiles:
    active: dev
#监控指标

server:
    #端口
    port: 8088

#注册中心地址及账号密码
eurekaServer:
  user: root
  password: root
hystrix:
  command:
    default:
      execution:
        isolation:
        thread:
        #毫秒单位
        timeoutInMilliseconds: 10000
eureka:
  instance:
    instance-id: localhost:${server.port}
    hostname: localhost
    prefer-ip-address: true
    #lease-renewal-interval-in-seconds: 5
    #lease-expiration-duration-in-seconds: 10
  client:
    #将此项目注册到Eureka服务
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eurekaServer.user}:${eurekaServer.password}@peer1:8761/eureka,http://${eurekaServer.user}:${eurekaServer.password}@peer2:8762/eureka,http://${eurekaServer.user}:${eurekaServer.password}@peer3:8763/eureka

info:
      status: OK